### ISSUE TITLE
Yaml parsing

### ISSUE THREAD

**Issue by icarob-eng** [icarob-eng/Estabilidade-IO#4]
Criar uma classe para parsing de Strings Yaml e gerar um objeto `Structure` com todos os valores inseridos no Yaml, incluindo constantes como `VERTICAL` e `HORIZONTAL`, tolerando falta de acentuação e sendo não sendo case sensitive. Em, suma, tudo que se precisa é:

```kotlin
fun structureFromYaml(val string: String): Structure
```

**Comment by ArthurValada** [comment]
Há algumas dúvidas que eu acho necessário esclarecer:

1. Mais de um dado estará inserido dentro de uma mesma string?
2. A função só terá uma string de entrada?
3. O exemplo mostrado foi apenas sugestivo ou possui, mesmo que vaga, semelhança com o produto final?
4. Tu quisestes dizer que a função terá parâmetros de entrada do tipo string e retorno de uma instância da classe structure, em suma?
5. Em qual módulo, digo..em qual parte ou segmentação tu recomendas que tal função se localize?
6. Não seria mais adequado um sistema de inserção de dados não-textual?

**Comment by icarob-eng** [comment]
- Sobre 1, 2 e 4: a `String` em questão será formatada em `yaml` e deverá conter todos os dados necessários para a formação de um objeto `Structure`, ver exemplo abaixo. Ela pode ser proveniente de um arquivo `.yaml` enviado pelo usuário ou um editor de texto dentro do app (isto precisa ser decidido em detalhes);

- Sobre 3: o método que precisa ser público dentro da classe. Os demais podem e (talvez devam) ser privados;

- Sobre 5: deves criar uma classe / módulo pra isto. Recomendação: acredito que todas as funcionalidades serão estáticas, então sugiro utilizar de um `companion object` para permitir que os métodos da classe possam ser chamados sem precisar de uma instância da classe. Vide o que fiz em `MathUtils`;

- Sobre 6: planejamos usar os dois, utilizando o `yaml` tanto para permitir o compartilhamento de projetos entre usuários, quanto para permitir a visualização do projeto como um todo. Pode não parecer, mas perguntas para o público alvo tiveram respostas mais positivas do que se espera, quanto à entrada de dados assim.

```yaml
---
projeto: nome do projeto # opcional
nos:
   A: [0,0]
   B: [4,0]
   C:
      x: 5
      y: 0

apoios:
   A: # apoio no nó A
      gênero: 1
      direção: vertical
   B:
      gênero: 2
      direção: [0,1]

barras:
   - [A,B]
   - [B,C]

cargas:
   F1:
      nó: A  # único nó = carga pontual
      direção: horizontal
      módulo: 200
   F2:
      nó: [A,C]  # dois nós = carga distribuída
      direção: vertical
      módulo: -20
   F3:
      nó: B
      vetor: [0,-100]
...
```
